NFT gated spaces - only NFT holders can publish posts
decensored/contracts pull request #11
Opened 2022-02-05 20:52 UTC by huhn511

- Added `nft_address` attribute to Spaces, for public space use address: `0x0000000000000000000000000000000000000000` 
- Added `connect_metamask_address` function - call it via metamask and the address gets stored into the decensored account

2022-02-06 13:31 UTC, mikrohash requested changes

2022-02-06 13:31 UTC, mikrohash commented on contracts/Accounts.sol
> +        require(account._address != msg.sender, "You need to send this message via Metamask");
`account._address` is not the Metamask address, but the address belonging to the Decensored private key, which is stored in the browsers localStorage.

2022-02-06 13:31 UTC, mikrohash commented on contracts/Accounts.sol
> +        require(account._address == msg.sender, "You dont have permission to do this!");
Views should not have `require` in my opinion. As everything is public on the blockchain, anyways.

2022-02-06 13:31 UTC, mikrohash commented on contracts/Posts.sol
> +        require(!isAllowedToPost, "Cannot submit post: you don't have the rights to post in this space!");
require not allowed to post?
The first argument of require must be true, else it throws an error.
You probably meant to write this without the negation :)

2022-02-06 13:31 UTC, mikrohash commented on contracts/Spaces.sol
> +        }
`return ownerTokenCount < 0;`

2022-02-06 13:43 UTC, huhn511 commented on contracts/Accounts.sol
> +        require(account._address != msg.sender, "You need to send this message via Metamask");
Yeh - the require just fails, if the user tries to sign this message with the decensored address - so this function needs to be called by metamask, and then the address will be stored to the decensored account.

2022-02-06 13:44 UTC, huhn511 commented on contracts/Accounts.sol
> +        require(account._address == msg.sender, "You dont have permission to do this!");
True 👍

2022-02-06 13:47 UTC, huhn511 commented on contracts/Spaces.sol
> +        }
Hmm, the function has the name "is_allowed" and should return "true/false", otherwise we should think to raname it to "balanceOfNFTsbyAccount" or something. What do you think?

2022-02-06 13:53 UTC, huhn511 commented on contracts/Posts.sol
> +        require(!isAllowedToPost, "Cannot submit post: you don't have the rights to post in this space!");
Fixed it :)

2022-02-07 15:03 UTC, mikrohash reviewed
Code looks good!
Let's add some unit tests to `test/test_accounts.js`
Then we can approve, merge, deploy and test with the front-end :)

2022-02-08 14:39 UTC, mikrohash approved these changes

2022-02-08 14:39 UTC, merged